spring:
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
  cloud:
    stream:
      override-cloud-connectors: true
      bindings:
        google-channel:
          destination: demo
          producer:
            error-channel-enabled: true
          #contentType: application/text
        microsoft-channel:
          destination: demo
          #contentType: application/text
        error:
          destination: myErrors
      rabbit:
        bindings:
          google-channel:
            producer:
              exchange-type: direct
              routing-key-expression: headers.routingKey
          microsoft-channel:
            producer:
              exchange-type: direct
              routing-key-expression: headers.routingKey
#          error:
#            producer:
#              exchangeType: direct
#              routing-key-expression: headers.routingKey


#
#authentication_failure_close:	true
#basic.nack:	true
#connection.blocked:	true
#consumer_cancel_notify:	true
#exchange_exchange_bindings:	true
#publisher_confirms:	true
